### ISSUE TITLE
Cannot get `appState.initialPosition` 

### ISSUE THREAD

**Issue by farrelanelca** [Santos-Enoque/uber_clone_with_flutter#10]
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
√ Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter (12726): GET USER METHOD RUNNING =========
E/flutter (12726): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (12726): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (12726): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (12726): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter (12726): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter (12726): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (12726): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter (12726): #4      LocationPermissions.checkPermissionStatus (package:location_permissions/src/location_permissions.dart:38:30)
E/flutter (12726): #5      Geolocator._getLocationPermission (package:geolocator/geolocator.dart:191:10)
E/flutter (12726): #6      Geolocator.getCurrentPosition (package:geolocator/geolocator.dart:91:47)
E/flutter (12726): #7      AppState._getUserLocation (package:uber_clone/states/app_state.dart:32:10)
E/flutter (12726): #8      new AppState (package:uber_clone/states/app_state.dart:25:5)
E/flutter (12726): #9      main (package:uber_clone/main.dart:8:43)
E/flutter (12726): #10     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (12726): #11     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (12726): #12     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (12726): #13     _runZoned (dart:async/zone.dart:1518:10)
E/flutter (12726): #14     runZoned (dart:async/zone.dart:1502:12)
E/flutter (12726): #15     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (12726): #16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter (12726): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (12726): 
![Screenshot_2020-03-31-11-38-31-45_fcacf24cf1a6253dd7c46eef7910b46a](https://user-images.githubusercontent.com/42790915/77987606-7f5d1b00-7344-11ea-9dd4-b65fad72f0ac.png)

**Comment by griotdonation** [comment]
hi, did you resolve this?I'm having the same issue.

**Comment by hrithik-cloud** [comment]
hey ! can you please tell me how did you move forward after singup page. I cloned the project and opened it in android studio, but im not able to run it
